<div class="signcontainer">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>项目</th>
            <th>数量</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>注册高校总数</td>
            <td><?=$nschools?></td>
        </tr>
        <tr>
            <td>已经确认高校总数</td>
            <td><?=$nverified?></td>
        </tr>
        <tr>
            <td>已经缴费高校总数</td>
            <td><?=$npaid?></td>
        </tr>
        <tr>
            <td>目前参赛人数（含未确认）</td>
            <td><?=$nrace?></td>
        </tr>
        <tr>
            <td>目前观赛人数（含未确认）</td>
            <td><?=$nlook?></td>
        </tr>
        <tr>
            <td>男子大众组人数（含未确认）</td>
            <td><?=$nmale?></td>
        </tr>
        <tr>
          <td>男子公路组人数（含未确认）</td>
          <td><?=$nmale_rdb?></td>
        </tr>
        <tr>
            <td>男子精英组人数（含未确认）</td>
            <td><?=$nmale_expert?></td>
        </tr>
        <tr>
            <td>女子组人数（含未确认）</td>
            <td><?=$nfemale?></td>
        </tr>
        <tr>
            <td>团体赛队伍数量</td>
            <td><?=$nteams?></td>
        </tr>
        <tr>
            <td>旅馆人数</td>
            <td><?=$hotel?></td>
        </tr>
        <tr>
            <td>自带帐篷露营人数</td>
            <td><?=$tent?></td>
        </tr>
        <tr>
            <td>第一天晚餐人数</td>
            <td><?=$dinner?></td>
        </tr>
        <tr>
            <td>第二天午餐人数</td>
            <td><?=$lunch?></td>
        </tr>
        </tbody>
    </table>
</div>